project:
  type: website

website:
  title: "bpp_portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme:
      - cosmo
      - brand
    page-layout: full
    css: styles.css
    toc: true
	



